// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpSys-hF_fAn9dA0vBKoVcsmOWq0pypTo',
    appId: '1:303607562709:web:672fe49205d96c2ffebd5c',
    messagingSenderId: '303607562709',
    projectId: 'foode-flutter-uic',
    authDomain: 'foode-flutter-uic.firebaseapp.com',
    storageBucket: 'foode-flutter-uic.firebasestorage.app',
    measurementId: 'G-RVW2SSZWFM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5rbLO5pVCT1uhaeq5VlmtHM4j7AahZIs',
    appId: '1:303607562709:android:4eccf2a25779ad12febd5c',
    messagingSenderId: '303607562709',
    projectId: 'foode-flutter-uic',
    storageBucket: 'foode-flutter-uic.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdOaTzG6-x5Rzy1U3Nwni9atSKitQKz2g',
    appId: '1:303607562709:ios:1fa107756078f647febd5c',
    messagingSenderId: '303607562709',
    projectId: 'foode-flutter-uic',
    storageBucket: 'foode-flutter-uic.firebasestorage.app',
    iosBundleId: 'inc.futuretechnologies.presidentftinc.flutter.foode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdOaTzG6-x5Rzy1U3Nwni9atSKitQKz2g',
    appId: '1:303607562709:ios:1fa107756078f647febd5c',
    messagingSenderId: '303607562709',
    projectId: 'foode-flutter-uic',
    storageBucket: 'foode-flutter-uic.firebasestorage.app',
    iosBundleId: 'inc.futuretechnologies.presidentftinc.flutter.foode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpSys-hF_fAn9dA0vBKoVcsmOWq0pypTo',
    appId: '1:303607562709:web:ece6588df6b9d20efebd5c',
    messagingSenderId: '303607562709',
    projectId: 'foode-flutter-uic',
    authDomain: 'foode-flutter-uic.firebaseapp.com',
    storageBucket: 'foode-flutter-uic.firebasestorage.app',
    measurementId: 'G-9C0C0EGNBG',
  );
}
